Resources:
  ordersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      # I'm are too poor to enable point in time recovery
      # PointInTimeRecoverySpecification:
      #   PointInTimeRecoveryEnabled: true
