Resources:
  ordersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # I'm are too poor to enable point in time recovery
      # PointInTimeRecoverySpecification:
      #   PointInTimeRecoveryEnabled: true
