name: CD

on:
  push:
    branches:
      - "*"

jobs:
  cd:
    name: cd-workflow
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Install Serverless Framework
        run: npm i -g serverless
      
      - name: Install the dependecy
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          
      
          
      - name: Deploy resurce-oreders
        run: cd resurces/orders && sls deploy --stage ${{ github.head_ref || github.ref_name }} 
      
      - name: Deploy service-api
        run: cd services/api && sls deploy --stage ${{ github.head_ref || github.ref_name }} 
      
      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
          dir: 'services/api'
